"""
Link: https://projecteuler.net/problem=2
Description:
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""
from itertools import takewhile

from utilities import fibonacci


def is_less_than(cutoff):
    def inner(num):
        return num < cutoff
    return inner


def solution():
    return sum(x for x in takewhile(is_less_than(4000000), fibonacci()) if not x % 2)


if __name__ == "__main__":
    print solution()
